In [3]:
import numpy as np
centers_array  = np.array([[ 81.7965449 , 228.43339893, 150.60398445],
 [ 89.34512045, 218.48233683,  83.80419297],
 [ 87.34319613, 216.73747829, 117.28815204],
 [ 77.6152908 , 242.69002069, 181.65315701],
 [ 82.39648499, 248.61073858,  54.40004907],
 [ 76.49260917, 253.29242395, 211.02858779],
 [ 66.14285714, 226.71428571, 230.57142857]])
z_order = np.argsort(centers_array[:, 0]) # x
print(centers_array, z_order)

[[ 81.7965449  228.43339893 150.60398445]
 [ 89.34512045 218.48233683  83.80419297]
 [ 87.34319613 216.73747829 117.28815204]
 [ 77.6152908  242.69002069 181.65315701]
 [ 82.39648499 248.61073858  54.40004907]
 [ 76.49260917 253.29242395 211.02858779]
 [ 66.14285714 226.71428571 230.57142857]] [6 5 3 0 4 2 1]


In [4]:
z_order = np.argsort(centers_array[:, 1]) # y
print(centers_array, z_order)

[[ 81.7965449  228.43339893 150.60398445]
 [ 89.34512045 218.48233683  83.80419297]
 [ 87.34319613 216.73747829 117.28815204]
 [ 77.6152908  242.69002069 181.65315701]
 [ 82.39648499 248.61073858  54.40004907]
 [ 76.49260917 253.29242395 211.02858779]
 [ 66.14285714 226.71428571 230.57142857]] [2 1 6 0 3 4 5]


In [5]:
z_order = np.argsort(centers_array[:, 2]) # z
print(centers_array, z_order)

[[ 81.7965449  228.43339893 150.60398445]
 [ 89.34512045 218.48233683  83.80419297]
 [ 87.34319613 216.73747829 117.28815204]
 [ 77.6152908  242.69002069 181.65315701]
 [ 82.39648499 248.61073858  54.40004907]
 [ 76.49260917 253.29242395 211.02858779]
 [ 66.14285714 226.71428571 230.57142857]] [4 1 2 0 3 5 6]
